/**
 * Trace Event Grammar + TraceEmitter + RunSequencer.
 * Truth Model ref: Deliverable 3 — BC-020 through BC-028
 * Truth Model v1.1 ref: Revised BC-023 (32 events), New BC-029 (handoff outcomes in trace),
 *                        New BC-029.1 (RunSequencer dual-mode), New INV-X13 (GovernanceQueryContext)
 *
 * Phase: 0A (Foundation)
 * Build Order: 3 (depends on Deliverable 2)
 *
 * Constitutional Sources: Table 6, Principle 7, Principle 15, Amendment A4
 * Binding Doctrine: Binding 8 (32 events), Binding 12 (CorrelationId), Binding 14 (trace failure)
 *
 * BC-020: TraceEmitter is SEPARATE from EventBus. Does NOT extend EventBus.
 * INV-023: 32 constitutional trace events and 39 domain events are distinct systems.
 */

import type { DatabaseConnection } from './database.js';
import type { TenantId, MissionId, TaskId, AgentId, OperationContext, Result } from './common.js';
import type {
  RunId, AttemptId, TraceEventId, CorrelationId,
  MissionContractId, SupervisorDecisionId, SuspensionRecordId,
  HandoffId, EvalCaseId, CapabilityManifestId,
} from './governance_ids.js';
import type { MissionLifecycleState, TaskLifecycleState } from './lifecycle.js';
import type { HandoffAcceptanceOutcome, HandoffRejectionReason, SupervisorType, DecisionOutcome } from './supervisor.js';

// ─── Trace Event Type Union (BC-023, revised v1.1) ───

/**
 * BC-023 (revised v1.1): Typed string union of exactly 32 event types.
 * Source: Design Source §3C (28) + Binding 8 (+3 memory) + Binding 15 (+1 handoff.parent-suspended)
 *
 * Untyped string allows misspelled event types that compile but are never matched.
 */
export type TraceEventType =
  // Mission lifecycle (5)
  | 'mission.created'
  | 'mission.transition'
  | 'mission.completed'
  | 'mission.failed'
  | 'mission.revoked'
  // Task lifecycle (4)
  | 'task.created'
  | 'task.transition'
  | 'task.completed'
  | 'task.skipped'
  // Attempt lifecycle (4)
  | 'attempt.started'
  | 'attempt.succeeded'
  | 'attempt.failed'
  | 'attempt.abandoned'
  // Handoff lifecycle (5) — includes handoff.parent-suspended (Binding 15, BC-052)
  | 'handoff.issued'
  | 'handoff.accepted'
  | 'handoff.returned'
  | 'handoff.rejected'
  | 'handoff.parent-suspended'
  // Suspension (2)
  | 'suspension.entered'
  | 'suspension.resolved'
  // Supervision (1)
  | 'supervision.decision'
  // Claims (4)
  | 'claim.asserted'
  | 'claim.grounded'
  | 'claim.challenged'
  | 'claim.retracted'
  // Eval (1)
  | 'eval.scored'
  // Capability (1)
  | 'capability.executed'
  // Artifact (1)
  | 'artifact.created'
  // Budget (1)
  | 'budget.consumed'
  // Memory governance (3) — Binding 8
  | 'memory.published'
  | 'memory.tombstoned'
  | 'memory.promoted';

// ─── Trace Event Entity (BC-022) ───

/**
 * BC-022: Every TraceEvent has this typed shape (not Record<string, unknown>).
 * All Table 6 fields present. Immutable once created (INV-020).
 */
export interface TraceEvent {
  readonly traceEventId: TraceEventId;
  readonly runId: RunId;
  readonly runSeq: number;
  readonly spanSeq: number;
  readonly parentEventRef?: TraceEventId;
  readonly forkOfRunId?: RunId;
  readonly forkFromEventRef?: TraceEventId;
  readonly correlationId: CorrelationId;
  readonly version: string;
  readonly type: TraceEventType;
  readonly tenantId: TenantId;
  readonly timestamp: string;
  readonly payload: TraceEventPayload;
  /** INV-X04: Governance schema version */
  readonly schemaVersion: string;
}

/**
 * Input shape for TraceEmitter.emit() — fields generated by the system
 * (traceEventId, runSeq, spanSeq, timestamp) are NOT provided by caller.
 */
export interface TraceEventInput {
  readonly runId: RunId;
  readonly parentEventRef?: TraceEventId;
  readonly forkOfRunId?: RunId;
  readonly forkFromEventRef?: TraceEventId;
  readonly correlationId: CorrelationId;
  readonly type: TraceEventType;
  readonly payload: TraceEventPayload;
}

// ─── Trace Event Payload (BC-024, BC-029) ───

/**
 * BC-024: Discriminated union pattern. Each TraceEventType has a typed payload.
 * BC-029 (v1.1): handoff.accepted includes typed acceptanceOutcome,
 *                handoff.rejected includes typed rejectionReason.
 * BC-052 (v1.1): handoff.parent-suspended includes suspension cascade payload.
 */
export type TraceEventPayload =
  // Mission events
  | { readonly type: 'mission.created'; readonly missionId: MissionId; readonly contractId?: MissionContractId; readonly agentId: AgentId }
  | { readonly type: 'mission.transition'; readonly missionId: MissionId; readonly fromState: MissionLifecycleState; readonly toState: MissionLifecycleState }
  | { readonly type: 'mission.completed'; readonly missionId: MissionId; readonly contractSatisfied: boolean }
  | { readonly type: 'mission.failed'; readonly missionId: MissionId; readonly reason: string }
  | { readonly type: 'mission.revoked'; readonly missionId: MissionId; readonly revokedBy: string }
  // Task events
  | { readonly type: 'task.created'; readonly taskId: TaskId; readonly missionId: MissionId }
  | { readonly type: 'task.transition'; readonly taskId: TaskId; readonly fromState: TaskLifecycleState; readonly toState: TaskLifecycleState }
  | { readonly type: 'task.completed'; readonly taskId: TaskId; readonly missionId: MissionId }
  | { readonly type: 'task.skipped'; readonly taskId: TaskId; readonly missionId: MissionId; readonly reason: string }
  // Attempt events
  | { readonly type: 'attempt.started'; readonly attemptId: AttemptId; readonly taskId: TaskId; readonly runId: RunId }
  | { readonly type: 'attempt.succeeded'; readonly attemptId: AttemptId; readonly taskId: TaskId }
  | { readonly type: 'attempt.failed'; readonly attemptId: AttemptId; readonly taskId: TaskId; readonly errorCode: string }
  | { readonly type: 'attempt.abandoned'; readonly attemptId: AttemptId; readonly taskId: TaskId; readonly suspensionRecordId: SuspensionRecordId }
  // Handoff events (BC-029, BC-052)
  | { readonly type: 'handoff.issued'; readonly handoffId: HandoffId; readonly delegatorAgentId: AgentId; readonly delegateAgentId: AgentId }
  | { readonly type: 'handoff.accepted'; readonly handoffId: HandoffId; readonly acceptanceOutcome: HandoffAcceptanceOutcome }
  | { readonly type: 'handoff.returned'; readonly handoffId: HandoffId; readonly returnReason: string }
  | { readonly type: 'handoff.rejected'; readonly handoffId: HandoffId; readonly rejectionReason: HandoffRejectionReason }
  | { readonly type: 'handoff.parent-suspended'; readonly handoffId: HandoffId; readonly parentMissionId: MissionId; readonly childTaskId: TaskId; readonly suspensionRecordId: SuspensionRecordId; readonly delegateAgentId: AgentId }
  // Suspension events
  | { readonly type: 'suspension.entered'; readonly suspensionRecordId: SuspensionRecordId; readonly targetType: string; readonly targetId: string }
  | { readonly type: 'suspension.resolved'; readonly suspensionRecordId: SuspensionRecordId; readonly decisionId: SupervisorDecisionId }
  // Supervision events
  | { readonly type: 'supervision.decision'; readonly decisionId: SupervisorDecisionId; readonly supervisorType: SupervisorType; readonly outcome: DecisionOutcome }
  // Claim events
  | { readonly type: 'claim.asserted'; readonly claimId: string; readonly agentId: AgentId }
  | { readonly type: 'claim.grounded'; readonly claimId: string; readonly evidenceCount: number }
  | { readonly type: 'claim.challenged'; readonly claimId: string; readonly challengerId: AgentId }
  | { readonly type: 'claim.retracted'; readonly claimId: string; readonly reason: string }
  // Eval events
  | { readonly type: 'eval.scored'; readonly evalCaseId: EvalCaseId; readonly score: number }
  // Capability events
  | { readonly type: 'capability.executed'; readonly capabilityType: string; readonly manifestId: CapabilityManifestId; readonly trustTier: string }
  // Artifact events
  | { readonly type: 'artifact.created'; readonly artifactId: string; readonly missionId: MissionId; readonly taskId: TaskId }
  // Budget events
  | { readonly type: 'budget.consumed'; readonly missionId: MissionId; readonly tokensConsumed: number; readonly remaining: number }
  // Memory governance events (Binding 8)
  | { readonly type: 'memory.published'; readonly entryId: string; readonly taskId: TaskId }
  | { readonly type: 'memory.tombstoned'; readonly entryId: string; readonly taskId: TaskId }
  | { readonly type: 'memory.promoted'; readonly entryId: string; readonly claimId: string };

// ─── TraceEmitter Interface (BC-021) ───

/**
 * BC-021: TraceEmitter — SEPARATE from EventBus (BC-020).
 * BC-025: correlationId generated ONCE at operation level, passed to both EventBus and TraceEmitter.
 * BC-027: Emission within SQLite transactions is transaction-coupled.
 * BC-028: Emission outside transactions is async best-effort with retry.
 */
export interface TraceEmitter {
  emit(conn: DatabaseConnection, ctx: OperationContext, event: TraceEventInput): Result<TraceEventId>;
  readonly sequencer: RunSequencer;
}

/**
 * BC-021, BC-029.1 (v1.1): Dual-mode sequencer.
 *
 * Transaction-coupled mode (default): reads MAX(runSeq) within SQLite transaction.
 * Async mode: uses in-memory atomic counter per RunId.
 *
 * BC-013: runSeq is strictly monotonically increasing — no gaps, no duplicates.
 * BC-014: In a forked run, runSeq starts at 1 (not ancestor's last).
 */
export interface RunSequencer {
  nextRunSeq(runId: RunId): number;
  nextSpanSeq(runId: RunId, spanIndex: number): number;
}

// ─── Trace Event Store ───

/**
 * Trace event persistence operations.
 * INV-020: Trace events are immutable — no update or delete.
 * INV-021: (runId, runSeq) is unique.
 */
export interface TraceEventStore {
  insert(conn: DatabaseConnection, event: TraceEvent): Result<TraceEvent>;
  getByRun(conn: DatabaseConnection, runId: RunId): Result<readonly TraceEvent[]>;
  getByCorrelation(conn: DatabaseConnection, correlationId: CorrelationId): Result<readonly TraceEvent[]>;
}

// ─── Governance Query Context (INV-X13, v1.1) ───

/**
 * INV-X13 (v1.1): Every SC-G governance query response includes this context.
 * Enables agents to assess freshness, completeness, and policy version.
 * Source: Binding 11 (SC-G Response Context).
 */
export interface GovernanceQueryContext {
  readonly asOfRunSeq: number;
  readonly policyVersionHard: string;
  readonly policyVersionSoft: string;
  readonly queryTimestamp: string;
  readonly queryScope: string;
  readonly sourceSystems: readonly string[];
  readonly completeness: 'complete' | 'partial';
  readonly missingSources?: ReadonlyArray<{
    readonly system: string;
    readonly reason: string;
  }>;
}
