// @governance SolisForge Protocol v1.4 — Sole Governing Doctrine
// @traceability contracts/LIMEN_V5_INTEGRATION_CONTRACT.md §5.1
/**
 * FR-001: Output Primitives API — Convenience namespace for semantic output.
 *
 * Provides `output.assert()` and `output.query()` methods that sit on the
 * Limen API object. These are thin wrappers over ClaimApi that:
 *   1. Validate the primitive against its Zod schema (fail-fast before CCP)
 *   2. Serialize the primitive to JSON for claim storage
 *   3. Parse JSON back to typed objects on query
 *
 * Architecture: This is the "store" layer in the three-file pattern.
 * Output types are defined in cognitive/output_primitives.ts (contract).
 * This file implements the convenience API (implementation).
 *
 * Governance boundary (I-17): Only imports ClaimApi, never ClaimSystem/ClaimStore.
 *
 * Spec ref: v4.0.0 Phase 4 FR-001
 * QAL: 3 (Knowledge integrity. Failure = corrupted intelligence.)
 */

import type { Result } from '../../kernel/interfaces/index.js';
import type { MissionId, TaskId } from '../../kernel/interfaces/index.js';
import type { TimeProvider } from '../../kernel/interfaces/time.js';
import type { ClaimApi } from '../interfaces/api.js';
import type { TenantScopedConnection } from '../../kernel/tenant/tenant_scope.js';
import type { BeliefView, RememberResult } from '../convenience/convenience_types.js';

import {
  isOutputPredicate,
  validateOutputPrimitive,
  VALID_OUTPUT_PREDICATES,
} from '../../cognitive/output_primitives.js';
// Note: isOutputPredicate still used in queryOutput below; validateOutputPrimitive
// checks namespace membership internally, so assertOutput no longer needs a separate guard.

// ── Result Helpers ──

function ok<T>(value: T): Result<T> {
  return { ok: true, value };
}

function err<T>(code: string, message: string): Result<T> {
  return { ok: false, error: { code, message, spec: 'FR-001' } };
}

// ============================================================================
// Types
// ============================================================================

export interface OutputAssertOptions {
  /** Subject URN. Defaults to 'entity:output:<auto-generated>'. */
  readonly subject?: string;
  /** Confidence [0.0, 1.0]. Subject to maxAutoConfidence cap. */
  readonly confidence?: number;
}

export interface OutputQueryOptions {
  /** Filter by subject URN pattern. */
  readonly subject?: string;
  /** Max results. Default: 50. */
  readonly limit?: number;
}

/**
 * The output namespace on the Limen API object.
 */
export interface OutputApi {
  /**
   * Assert a structured output primitive as a governed claim.
   *
   * Validates the primitive against its Zod schema, serializes to JSON,
   * and stores via the CCP assertion pipeline.
   *
   * @param predicate - Output predicate (e.g. 'output.judgment')
   * @param primitive - The structured primitive object
   * @param options - Optional subject, confidence overrides
   */
  assert(predicate: string, primitive: object, options?: OutputAssertOptions): Result<RememberResult>;

  /**
   * Query output primitives by type.
   *
   * @param type - Output predicate to filter (e.g. 'output.judgment'). If omitted, returns all output.* claims.
   * @param options - Query options (subject filter, limit)
   */
  query(type?: string, options?: OutputQueryOptions): Result<readonly BeliefView[]>;
}

// ============================================================================
// Dependencies
// ============================================================================

export interface OutputApiDeps {
  readonly claims: ClaimApi;
  readonly getConnection: () => TenantScopedConnection;
  readonly time: TimeProvider;
  readonly missionId: MissionId;
  readonly taskId: TaskId | null;
  readonly maxAutoConfidence: number;
}

// ============================================================================
// Factory
// ============================================================================

/**
 * Create the output API namespace.
 *
 * Returns a frozen object with assert() and query() methods.
 */
export function createOutputApi(deps: OutputApiDeps): OutputApi {
  const { claims, time, missionId, taskId, maxAutoConfidence } = deps;

  function assertOutput(
    predicate: string,
    primitive: object,
    options?: OutputAssertOptions,
  ): Result<RememberResult> {
    // 1. Validate predicate + schema in one call (namespace membership checked internally)
    const validation = validateOutputPrimitive(predicate, primitive);
    if (!validation.ok) {
      return validation as Result<RememberResult>;
    }

    // 3. Serialize to JSON string for claim storage
    const jsonValue = JSON.stringify(primitive);

    // 4. Build subject URN
    const subject = options?.subject ?? `entity:output:${Date.now().toString(36)}`;

    // 5. Compute confidence (respect cap)
    const confidence = options?.confidence !== undefined
      ? Math.min(options.confidence, maxAutoConfidence)
      : maxAutoConfidence;

    // 6. Assert via ClaimApi
    const result = claims.assertClaim({
      subject,
      predicate,
      object: { type: 'json', value: jsonValue },
      confidence,
      validAt: time.nowISO(),
      missionId,
      taskId,
      groundingMode: 'runtime_witness',
      evidenceRefs: [],
      runtimeWitness: {
        witnessType: 'output_primitive',
        witnessedValues: { primitiveType: predicate.split('.')[1] ?? 'unknown' },
        witnessTimestamp: time.nowISO(),
      },
    });

    if (!result.ok) {
      return result as Result<RememberResult>;
    }

    return ok({
      claimId: result.value.claim.id,
      subject,
      predicate,
      confidence: result.value.claim.confidence,
    } as RememberResult);
  }

  function queryOutput(
    type?: string,
    options?: OutputQueryOptions,
  ): Result<readonly BeliefView[]> {
    // If type is provided, validate it
    if (type !== undefined) {
      if (!isOutputPredicate(type)) {
        return err('INVALID_OUTPUT_PRIMITIVE',
          `Type "${type}" is not in the output.* namespace`);
      }
      if (!VALID_OUTPUT_PREDICATES.has(type)) {
        return err('UNKNOWN_OUTPUT_PREDICATE',
          `Unknown output type: "${type}". Valid types: ${[...VALID_OUTPUT_PREDICATES].join(', ')}`);
      }
    }

    // Query claims via ClaimApi
    const predicate = type ?? 'output.*';
    const limit = options?.limit ?? 50;

    const result = claims.queryClaims({
      predicate,
      subject: options?.subject ?? null,
      limit,
      status: 'active',
    });

    if (!result.ok) {
      return result as Result<readonly BeliefView[]>;
    }

    // Transform ClaimQueryResult claims to BeliefView objects
    const beliefs: BeliefView[] = result.value.claims.map(item => ({
      claimId: item.claim.id,
      subject: item.claim.subject,
      predicate: item.claim.predicate,
      value: typeof item.claim.object.value === 'string'
        ? item.claim.object.value
        : JSON.stringify(item.claim.object.value),
      confidence: item.claim.confidence,
      validAt: item.claim.validAt,
      createdAt: item.claim.createdAt,
      effectiveConfidence: item.effectiveConfidence,
      freshness: item.freshness,
      stability: item.claim.stability,
      lastAccessedAt: item.claim.lastAccessedAt,
      accessCount: item.claim.accessCount,
      reasoning: item.claim.reasoning,
      superseded: item.superseded,
      disputed: item.disputed,
      reviewNeeded: item.reviewNeeded,
    }));

    return ok(beliefs as readonly BeliefView[]);
  }

  // Note: NOT frozen here. The permission gateway (applyPermissionGateway) wraps
  // methods by reassigning them. deepFreeze runs after the gateway and freezes everything.
  return {
    assert: assertOutput,
    query: queryOutput,
  };
}
