/**
 * FR-004: Telemetry API — Convenience namespace for operational telemetry.
 *
 * Provides `telemetry.record()` and `telemetry.query()` methods that sit on the
 * Limen API object. These are thin wrappers over ClaimApi that:
 *   1. Validate the telemetry data against its Zod schema (fail-fast before CCP)
 *   2. Serialize the data to JSON for claim storage
 *   3. Parse JSON back to typed objects on query
 *
 * Architecture: This is the "store" layer in the three-file pattern.
 * Telemetry types are defined in cognitive/telemetry_schemas.ts (contract).
 * This file implements the convenience API (implementation).
 *
 * Governance boundary (I-17): Only imports ClaimApi, never ClaimSystem/ClaimStore.
 *
 * Spec ref: v4.0.0 Phase 7 FR-004
 * QAL: 3 (Knowledge integrity. Failure = corrupted telemetry data.)
 */

import type { Result } from '../../kernel/interfaces/index.js';
import type { MissionId, TaskId } from '../../kernel/interfaces/index.js';
import type { TimeProvider } from '../../kernel/interfaces/time.js';
import type { ClaimApi } from '../interfaces/api.js';
import type { TenantScopedConnection } from '../../kernel/tenant/tenant_scope.js';
import type { BeliefView, RememberResult } from '../convenience/convenience_types.js';

import {
  isTelemetryPredicate,
  validateTelemetry,
  VALID_TELEMETRY_PREDICATES,
} from '../../cognitive/telemetry_schemas.js';

// ── Result Helpers ──

function ok<T>(value: T): Result<T> {
  return { ok: true, value };
}

function err<T>(code: string, message: string): Result<T> {
  return { ok: false, error: { code, message, spec: 'FR-004' } };
}

// ============================================================================
// Types
// ============================================================================

export interface TelemetryRecordOptions {
  /** Subject URN. Defaults to 'entity:telemetry:<auto-generated>'. */
  readonly subject?: string;
  /** Confidence [0.0, 1.0]. Subject to maxAutoConfidence cap. */
  readonly confidence?: number;
}

export interface TelemetryQueryOptions {
  /** Filter by subject URN pattern. */
  readonly subject?: string;
  /** Max results. Default: 50. */
  readonly limit?: number;
  /** ISO 8601 timestamp: only return claims created after this time. */
  readonly since?: string;
}

/**
 * The telemetry namespace on the Limen API object.
 */
export interface TelemetryApi {
  /**
   * Record a telemetry data point as a governed claim.
   *
   * Validates the data against its Zod schema, serializes to JSON,
   * and stores via the CCP assertion pipeline.
   *
   * @param type - Telemetry type: 'cost' | 'vital' | 'audit'
   * @param data - The telemetry data object
   * @param options - Optional subject, confidence overrides
   */
  record(type: 'cost' | 'vital' | 'audit', data: object, options?: TelemetryRecordOptions): Result<RememberResult>;

  /**
   * Query telemetry claims by type.
   *
   * @param type - Telemetry type to filter (e.g. 'cost'). If omitted, returns all telemetry.* claims.
   * @param options - Query options (subject filter, limit, since)
   */
  query(type?: string, options?: TelemetryQueryOptions): Result<readonly BeliefView[]>;
}

// ============================================================================
// Dependencies
// ============================================================================

export interface TelemetryApiDeps {
  readonly claims: ClaimApi;
  readonly getConnection: () => TenantScopedConnection;
  readonly time: TimeProvider;
  readonly missionId: MissionId;
  readonly taskId: TaskId | null;
  readonly maxAutoConfidence: number;
}

// ============================================================================
// Factory
// ============================================================================

/**
 * Create the telemetry API namespace.
 *
 * Returns an object with record() and query() methods.
 * NOT frozen here — the permission gateway wraps methods before deepFreeze.
 */
export function createTelemetryApi(deps: TelemetryApiDeps): TelemetryApi {
  const { claims, time, missionId, taskId, maxAutoConfidence } = deps;

  function recordTelemetry(
    type: 'cost' | 'vital' | 'audit',
    data: object,
    options?: TelemetryRecordOptions,
  ): Result<RememberResult> {
    // 1. Build predicate and validate
    const predicate = `telemetry.${type}`;
    const validation = validateTelemetry(predicate, data);
    if (!validation.ok) {
      return validation as Result<RememberResult>;
    }

    // 2. Serialize to JSON string for claim storage
    const jsonValue = JSON.stringify(data);

    // 3. Build subject URN
    const subject = options?.subject ?? `entity:telemetry:${Date.now().toString(36)}`; // clock-exempt: infrastructure ID generation

    // 4. Compute confidence (respect cap)
    const confidence = options?.confidence !== undefined
      ? Math.min(options.confidence, maxAutoConfidence)
      : maxAutoConfidence;

    // 5. Assert via ClaimApi
    const result = claims.assertClaim({
      subject,
      predicate,
      object: { type: 'json', value: jsonValue },
      confidence,
      validAt: time.nowISO(),
      missionId,
      taskId,
      groundingMode: 'runtime_witness',
      evidenceRefs: [],
      runtimeWitness: {
        witnessType: 'telemetry_record',
        witnessedValues: { telemetryType: type },
        witnessTimestamp: time.nowISO(),
      },
    });

    if (!result.ok) {
      return result as Result<RememberResult>;
    }

    return ok({
      claimId: result.value.claim.id,
      confidence: result.value.claim.confidence,
    } as RememberResult);
  }

  function queryTelemetry(
    type?: string,
    options?: TelemetryQueryOptions,
  ): Result<readonly BeliefView[]> {
    // If type is provided, validate it
    if (type !== undefined) {
      const fullPredicate = `telemetry.${type}`;
      if (!isTelemetryPredicate(fullPredicate)) {
        return err('INVALID_TELEMETRY',
          `Type "${type}" is not a valid telemetry type`);
      }
      if (!VALID_TELEMETRY_PREDICATES.has(fullPredicate)) {
        return err('UNKNOWN_TELEMETRY_PREDICATE',
          `Unknown telemetry type: "${type}". Valid types: ${[...VALID_TELEMETRY_PREDICATES].map(p => p.split('.')[1]).join(', ')}`);
      }
    }

    // Query claims via ClaimApi
    const predicate = type !== undefined ? `telemetry.${type}` : 'telemetry.*';
    const limit = options?.limit ?? 50;

    const result = claims.queryClaims({
      predicate,
      subject: options?.subject ?? null,
      limit,
      status: 'active',
    });

    if (!result.ok) {
      return result as Result<readonly BeliefView[]>;
    }

    // Transform ClaimQueryResult claims to BeliefView objects
    let beliefs: BeliefView[] = result.value.claims.map(item => ({
      claimId: item.claim.id,
      subject: item.claim.subject,
      predicate: item.claim.predicate,
      value: typeof item.claim.object.value === 'string'
        ? item.claim.object.value
        : JSON.stringify(item.claim.object.value),
      confidence: item.claim.confidence,
      validAt: item.claim.validAt,
      createdAt: item.claim.createdAt,
      effectiveConfidence: item.effectiveConfidence,
      freshness: item.freshness,
      stability: item.claim.stability,
      lastAccessedAt: item.claim.lastAccessedAt,
      accessCount: item.claim.accessCount,
      reasoning: item.claim.reasoning,
      superseded: item.superseded,
      disputed: item.disputed,
      reviewNeeded: item.reviewNeeded,
    }));

    // Apply 'since' filter if provided
    if (options?.since) {
      const sinceTime = new Date(options.since).getTime();
      if (!Number.isNaN(sinceTime)) {
        beliefs = beliefs.filter(b => new Date(b.createdAt).getTime() >= sinceTime);
      }
    }

    return ok(beliefs as readonly BeliefView[]);
  }

  // NOT frozen here — permission gateway wraps methods before deepFreeze.
  return {
    record: recordTelemetry,
    query: queryTelemetry,
  };
}
