/**
 * CrewAI Adapter — Barrel Exports
 *
 * Contract: CREWAI_ADAPTER_CONTRACT.md v1.0.0
 * Architecture: AGENT_ADAPTER_ARCHITECTURE.md v2.3.0
 */

export { LimenCrewAIAdapter } from './adapter.js';
export type { CrewAIAdapterConfig } from './config.js';
export { validateConfig, computeConfigDigest } from './config.js';
export {
  CrewAIAdapterError,
  notInitialized,
  alreadyInitialized,
  governanceRefusal,
  budgetExceeded,
  unknownTool,
  corePortUnavailable,
  auditFailure,
  serdeError,
  trustLevelInsufficient,
  capabilityNotDeclared,
  sessionNotFound,
  clientError,
  translationFailed,
  shutdownFailed,
  maxSessionsExceeded,
  internalError,
  branchConflict,
  timeProviderUnavailable,
  selectHighestPrecedence,
  toResultError,
} from './errors.js';
export { AdapterLifecycle } from './lifecycle.js';
export {
  normalizeHookContext,
  validateHookContext,
  translateToolToOperations,
  mapNativeEvent,
  mapLimenEvent,
  KNOWN_TOOLS,
} from './hooks.js';

// Re-export all types
export type {
  // Branded IDs
  TenantId,
  AgentId,
  SessionId,
  ClaimId,
  AgentBranchId,
  AdapterId,
  MissionId,
  TaskId,
  EventId,
  PolicyId,
  RelationshipId,
  // Enums and unions
  AgentTrustLevel,
  AgentCapability,
  ClassificationLevel,
  AgentFramework,
  TokenEncoding,
  MergeStrategy,
  ManualMergeResolution,
  FreshnessLabel,
  ClaimStatus,
  GroundingMode,
  ObjectType,
  EvidenceType,
  RelationshipType,
  ArchiveMode,
  AdapterLifecycleState,
  CrewAIAdapterErrorCode,
  AgentEvent,
  GovernanceAction,
  Permission,
  // Interfaces
  AgentSession,
  SessionSummary,
  OperationContext,
  StructuredContent,
  AgentMemoryOptions,
  AgentRecallQuery,
  AgentRecallOptions,
  AgentMemoryEntry,
  BeliefState,
  EvidenceRef,
  RelationshipRef,
  GovernanceContext,
  GovernanceVerdict,
  GovernanceDecision,
  SandboxConfig,
  AdapterSandboxDefaults,
  AdapterRefusalHint,
  RateLimitPolicy,
  TokenEstimate,
  TokenEstimator,
  PerformanceBudget,
  ActionDigest,
  AgentToolCall,
  LimenOperation,
  NativeAgentAction,
  ComputerAction,
  ActionBase,
  AuditLogEntry,
  RetentionPolicy,
  MergeConflict,
  ManualMergeState,
  AgentEventPayload,
  AgentEventHandler,
  AgentEventBus,
  LimenAgentClient,
  ComputerActionGovernor,
  Result,
  KernelError,
  // CrewAI local types
  CrewAIToolCallHookContext,
  CrewAIToolCall,
  CrewAIToolContext,
  CrewAIHookEvent,
  CrewAISessionStart,
  CrewAISessionEnd,
  CrewContext,
  RememberOptions,
  RecallResult,
  MergeResult,
  MergeConflictRecord,
  ManualMergeResolutionRequest,
  TokenBudgetConfig,
  RetryPolicy,
  AdapterHealth,
  CrewAIAuditDetails,
  MergeResultData,
} from './types.js';

export {
  TRUST_TO_CLEARANCE,
  TRUST_CONFIDENCE_CAPS,
  DEFAULT_RATE_LIMITS,
  ERROR_PRECEDENCE,
  NEVER_RETRYABLE,
} from './types.js';
