// @governance SolisForge Protocol v1.4 — Sole Governing Doctrine
// @traceability contracts/LIMEN_V5_INTEGRATION_CONTRACT.md §5.1
/**
 * Limen engine bootstrap for the A2A server.
 *
 * Reads ~/.limen/config.json (if it exists) and creates a Limen engine
 * instance with the configured settings. Falls back to sensible defaults
 * when no config file is present.
 *
 * Config file format (~/.limen/config.json):
 * {
 *   "dataDir": "/path/to/data",
 *   "providers": [{ "type": "anthropic", "baseUrl": "...", "models": [...] }],
 *   "masterKeyPath": "/path/to/master.key"
 * }
 *
 * Config contract is unified with CLI and MCP: masterKeyPath references
 * a binary key file (generated by `limen init`). If the key file is not
 * found, a random key is generated with a warning.
 *
 * Design: Bootstrap is separated from server.ts so that:
 *   1. The engine creation logic is testable independently.
 *   2. The config reading logic does not pollute the HTTP server.
 *   3. Future config sources (env vars, CLI flags) can be added here.
 */

import { readFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { randomBytes } from 'node:crypto';
import { createLimen } from 'limen-ai';
import type { Limen, LimenConfig, ProviderConfig } from 'limen-ai';

/** Raw shape of ~/.limen/config.json — unified with CLI and MCP. */
interface RawConfig {
  readonly dataDir?: string;
  readonly providers?: readonly ProviderConfig[];
  readonly masterKeyPath?: string;
}

/** Default data directory: ~/.limen/data */
const DEFAULT_DATA_DIR = join(homedir(), '.limen', 'data');

/** Config file path: ~/.limen/config.json */
const CONFIG_PATH = join(homedir(), '.limen', 'config.json');

/**
 * Read and parse the config file. Returns undefined if the file
 * does not exist or is malformed (with a warning to stderr).
 */
function readConfig(): RawConfig | undefined {
  if (!existsSync(CONFIG_PATH)) {
    return undefined;
  }

  try {
    const raw = readFileSync(CONFIG_PATH, 'utf-8');
    const parsed = JSON.parse(raw) as unknown;

    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
      process.stderr.write(`[limen-a2a] Warning: ${CONFIG_PATH} is not a JSON object, using defaults\n`);
      return undefined;
    }

    return parsed as RawConfig;
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    process.stderr.write(`[limen-a2a] Warning: Failed to read ${CONFIG_PATH}: ${message}, using defaults\n`);
    return undefined;
  }
}

/** Default master key path: ~/.limen/master.key */
const DEFAULT_MASTER_KEY_PATH = join(homedir(), '.limen', 'master.key');

/**
 * Bootstrap a Limen engine instance.
 *
 * Reads config from ~/.limen/config.json, applies defaults for missing
 * values, ensures the data directory exists, and creates the engine.
 *
 * Config contract is unified with CLI and MCP: masterKeyPath points to
 * a binary key file, not a hex-encoded string.
 *
 * Returns the initialized Limen instance, ready for API calls.
 */
export async function bootstrapEngine(): Promise<Limen> {
  const rawConfig = readConfig();

  // Resolve data directory
  const dataDir = rawConfig?.dataDir ?? DEFAULT_DATA_DIR;

  // Ensure data directory exists
  if (!existsSync(dataDir)) {
    mkdirSync(dataDir, { recursive: true });
  }

  // Resolve master key — unified contract: read binary file at masterKeyPath
  const masterKeyPath = rawConfig?.masterKeyPath ?? DEFAULT_MASTER_KEY_PATH;
  let masterKey: Buffer;
  if (existsSync(masterKeyPath)) {
    masterKey = readFileSync(masterKeyPath);
  } else {
    process.stderr.write(
      `[limen-a2a] Warning: master key not found at ${masterKeyPath}, generating random key. Run 'limen init' to create a persistent key.\n`,
    );
    masterKey = randomBytes(32);
  }

  // Build LimenConfig
  const config: LimenConfig = {
    dataDir,
    masterKey,
    providers: rawConfig?.providers,
  };

  // Create and return engine
  const limen = await createLimen(config);
  return limen;
}
